apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\kairy\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: coursesapi
  name: coursesapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: coursesapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\kairy\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: coursesapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__CoursesAPIContext
              value: Server=sqldata;Database=CoursesDB;User Id=sa;Password=My!P@ssw0rd1;Encrypt=False
            - name: MessageBroker__Host
              value: amqp://guest:guest@rabbitmq:5672
          image: coursesapi
          name: coursesapi
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
