apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\kairy\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: coursesapi
  name: coursesapi
spec:
  ports:
    - name: "5081"
      port: 5081
      targetPort: 8080
  selector:
    io.kompose.service: coursesapi
status:
  loadBalancer: {}
