apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\kairy\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: healthchecker
  name: healthchecker
spec:
  ports:
    - name: "5084"
      port: 5084
      targetPort: 8080
  selector:
    io.kompose.service: healthchecker
status:
  loadBalancer: {}
