apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\kairy\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: seq
  name: seq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: seq
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\kairy\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: seq
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
          image: datalust/seq:latest
          name: seq
          ports:
            - containerPort: 5341
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
