apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\kairy\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: seq
  name: seq
spec:
  ports:
    - name: "5341"
      port: 5341
      targetPort: 5341
    - name: "8081"
      port: 8081
      targetPort: 80
  selector:
    io.kompose.service: seq
status:
  loadBalancer: {}
