apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\kairy\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: studentsapi
  name: studentsapi
spec:
  ports:
    - name: "5082"
      port: 5082
      targetPort: 8080
  selector:
    io.kompose.service: studentsapi
status:
  loadBalancer: {}
